import React, { Component, ReactHTML, RefCallback, useEffect, useRef } from "react";
import { FC } from "react";

export type MockedComponent<PropType> = jest.MockedFunction<FC<PropType>> | jest.Mock<Component<PropType>>;

export type MockedElement<PropType = {}> = HTMLElement & {
    props: PropType, 
    component: MockedComponent<PropType>
};

export const mockElementTestId = 'rtl-mock-element';

type FunctionOrClassComponent<PropType> = FC<PropType> | (new (props: PropType) => Component<PropType>);

function ensureIsMock<PropType>(mockedComponent: FunctionOrClassComponent<PropType>) {
    if (!jest.isMockFunction(mockedComponent)) {
        throw new Error(`${mockedComponent.name} cannot be setup because it is not a Jest mock. Call "jest.mock('path/to/component')" first`);
    }
}

export interface MockComponentOptions {
    /**
     * The react element generated by the mock. `div` by default.
     */
    element?: keyof ReactHTML;
}

function createMockComponent<PropType>(mockedComponent: MockedComponent<PropType>, options?: MockComponentOptions): FC<PropType> {
    const MockImplementation: FC<PropType> = (props) => {
        const mockedElmentRef = useRef<MockedElement<PropType> | null>(null);
        useEffect(() => {
            if (mockedElmentRef.current) {
                mockedElmentRef.current.props = props;
            }
        }, [props]);

        const ref: RefCallback<HTMLDivElement> = (el) => {
            mockedElmentRef.current = el as unknown as MockedElement<PropType>;
            if (mockedElmentRef.current) {
                mockedElmentRef.current.component = mockedComponent; //TODO: fix me
            }
        };

        const type: keyof ReactHTML = options?.element ?? 'div';
        return React.createElement(type, {
            ref,
            'data-testid': mockElementTestId,
        }, props.children);
    };
    return MockImplementation;
}

export function setupMockComponent<PropType>(mockedComponent: FunctionOrClassComponent<PropType>, options?: MockComponentOptions) {
    ensureIsMock(mockedComponent);
    const MockImplementation = createMockComponent(mockedComponent as MockedComponent<PropType>, options);
    if (isClassComponent(mockedComponent)) {
        setupClassComponent(MockImplementation, mockedComponent as jest.Mock<Component<PropType>>);
    } else {
        const mockFunctionComponent = mockedComponent as jest.MockedFunction<FC<PropType>>;
        mockFunctionComponent.mockImplementation(MockImplementation);
    }
}

function setupClassComponent<PropType>(MockImplementation: FC<PropType>, mockedComponent: jest.Mock<Component<PropType>>) {
    class MockClassComponentWrapper extends Component<PropType> {
        render() {
            return <MockImplementation {...this.props} />;
        }
    }
    mockedComponent.mockImplementation((props: PropType) => new MockClassComponentWrapper(props));
}

function isClassComponent<PropType>(mockedComponent: FunctionOrClassComponent<PropType>) {
    return 'isReactComponent' in mockedComponent.prototype;
}
