name: Pull Requet Verify
on:
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - run: npm ci
      
      - name: Jest
        run: npm run jest

      - name: Vitest
        run: npm run vitest -- run

      - run: npm run compile